name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurar DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          curl -X GET -H "Authorization: Bearer ${DIGITALOCEAN_ACCESS_TOKEN}" https://api.digitalocean.com/v2/account

      - name: Configurar kubectl
        run: |
          doctl kubernetes cluster kubeconfig save "bizflow-cluster"

      - name: Desplegar en Kubernetes
        run: kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml
